name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    name: Build with ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'imbhargav5/nextbase-nextjs13-supabase-starter'}}
    steps:
      - name: 'Check if user has write access'
        uses: 'lannonbr/repo-permission-check-action@2.0.0'
        with:
          permission: 'write'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: github.event_name == 'pull_request'
        name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - if: github.event_name != 'pull_request'
        name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: ğŸš‚ CI Setup
        uses: ./.github/actions/ci-setup
      - run: yarn run build

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: ğŸ§ª Typecheck
        run: yarn run typecheck

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: ğŸ§¹ Lint
        run: yarn run lint

 